/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Gather: typeof import('./src/components/overview/Gather.vue')['default']
    HeadBar: typeof import('./src/components/bar/HeadBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconMailOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconMailOutline']
    IconPlusOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconPlusOutline']
    Menu: typeof import('./src/components/bar/menu.vue')['default']
    MenuBar: typeof import('./src/components/bar/MenuBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YkAvatar: typeof import('@yike-design/ui/es')['YkAvatar']
    YkBadge: typeof import('@yike-design/ui/es')['YkBadge']
    YkButton: typeof import('@yike-design/ui/es')['YkButton']
    YkSpace: typeof import('@yike-design/ui/es')['YkSpace']
    YkText: typeof import('@yike-design/ui/es')['YkText']
    YkTheme: typeof import('@yike-design/ui/es')['YkTheme']
    YkTitle: typeof import('@yike-design/ui/es')['YkTitle']
  }
}
